### PR TITLE
Drop odf-odp support (see, https://github.com/sugarlabs/portfolio-activity/pull/11#issuecomment-565670142)

### PR DESCRIPTION
**Pull request by srevinsaju**
This PR removes the odf-odp support and unitary support for PDF alone.

### CODE REVIEW

**Comment by srevinsaju** [comment]
https://github.com/sugarlabs/portfolio-activity/pull/11

**Comment by quozl** [comment]
Reviewed.  Some more code to remove;
* [x] `_get_image_list` is now without any callers, therefore so is `_next_image`.

**Comment by srevinsaju** [comment]
ok @quozl will remove that

**Comment by srevinsaju** [comment]
@quozl , fixed it on https://github.com/srevinsaju/portfolio-activity/pull/1/commits/3d5f45ed4255d5d969cf22018b2ee9eb74a63f7e and https://github.com/srevinsaju/portfolio-activity/pull/1/commits/4b18495e318fc015677e5b6aff06247597d870d9

**Comment by quozl** [comment]
I approve.  Proceed.

**Comment by srevinsaju** [comment]
@quozl merged

**Pull request merged**
